### ISSUE TITLE
Prepare repository for outside v2.0 contributions

### ISSUE THREAD

**Issue by benwiley4000** [benwiley4000/cassette#279]
With Hacktoberfest coming up there *could* be an influx of contributors who'd like to help out with the upcoming v2.0! Here's a checklist to minimize the friction:

- [x] Review and refine the API (#248)
- [x] Complete "rebranding"
- [x] Get the package split-up done so there isn't a lot of moving-around of files moving forward (#116)
- [x] Make an alpha release
- [x] Package-level README files
- [x] Set up documentation scaffolding with some basic API documentation and todo sections for deeper explanations (#34)
- [x] Refine example(s)
- [x] Set up test scaffolding (for snapshot testing and unit testing) so others can contribute tests (#35)
- [x] Run tests in CI (#183)
